<?php

namespace App\Services;

use App\Models\DanaSosialLimit;
use App\Models\DanaSosialSumber;
use App\Models\DompetKoperasi;
use App\Models\KlaimDanaSosial;
use App\Models\MutasiKas;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

class SocialFundService
{
    public function __construct(private readonly MutasiKasService $cash,private readonly AkuntansiService $accounting){}
    public function createDonation(array $data,int $userId):DanaSosialSumber{return DB::transaction(function()use($data,$userId){return DanaSosialSumber::query()->create(['kode_sumber'=>'DS-DON-'.strtoupper(Str::random(8)),'jenis'=>DanaSosialSumber::JENIS_DONASI,'dompet_id'=>$data['dompet_id'],'jumlah'=>$data['jumlah'],'saldo_tersedia'=>0,'tanggal'=>$data['tanggal'],'nomor_referensi'=>$data['nomor_referensi']??null,'keterangan'=>$data['keterangan'],'created_by'=>$userId,'status'=>'pending','idempotency_key'=>'dana-sosial:donasi:'.Str::uuid()]);});}
    public function approveDonation(DanaSosialSumber $source,int $userId):DanaSosialSumber{return DB::transaction(function()use($source,$userId){$locked=DanaSosialSumber::query()->with('dompet.akun')->lockForUpdate()->findOrFail($source->id);if($locked->status==='approved')return $locked;if($locked->jenis!==DanaSosialSumber::JENIS_DONASI)throw ValidationException::withMessages(['sumber'=>'Hanya donasi resmi yang memerlukan approval ini.']);if((int)$locked->created_by===$userId)throw ValidationException::withMessages(['sumber'=>'Pembuat donasi tidak boleh menyetujui record yang sama.']);$locked->update(['status'=>'approved','saldo_tersedia'=>$locked->jumlah,'approved_by'=>$userId,'approved_at'=>now()]);$this->cash->record(['idempotency_key'=>'dana-sosial:donasi:mutasi:'.$locked->id,'dompet_id'=>$locked->dompet_id,'tipe'=>'masuk','jumlah'=>$locked->jumlah,'keterangan'=>'Donasi resmi Dana Sosial','referensi_tipe'=>DanaSosialSumber::class,'referensi_id'=>$locked->id,'tanggal'=>$locked->tanggal]);$this->accounting->recordSocialDonation($locked,$userId);return $locked->fresh();});}
    public function saveLimit(array $data,int $userId):DanaSosialLimit{return DanaSosialLimit::query()->updateOrCreate(['kategori'=>$data['kategori']],['label'=>$data['label'],'maksimal'=>$data['maksimal'],'is_active'=>true,'updated_by'=>$userId]);}
    public function createClaim(array $data,int $userId):KlaimDanaSosial{return DB::transaction(function()use($data,$userId){$limit=DanaSosialLimit::query()->where('kategori',$data['kategori'])->where('is_active',true)->first();if(!$limit)throw ValidationException::withMessages(['kategori'=>'Batas maksimal kategori belum diatur.']);if((float)$data['nominal_diajukan']>(float)$limit->maksimal)throw ValidationException::withMessages(['nominal_diajukan'=>'Nominal melebihi batas maksimal kategori.']);return KlaimDanaSosial::query()->create([...$data,'kode_klaim'=>'KDS-'.strtoupper(Str::random(8)),'status'=>KlaimDanaSosial::MENUNGGU,'created_by'=>$userId,'idempotency_key'=>'dana-sosial:klaim:'.Str::uuid()]);});}
    public function approveClaim(KlaimDanaSosial $claim,int $userId):KlaimDanaSosial{return DB::transaction(function()use($claim,$userId){$locked=KlaimDanaSosial::query()->lockForUpdate()->findOrFail($claim->id);if($locked->status===KlaimDanaSosial::DISETUJUI)return $locked;if($locked->status!==KlaimDanaSosial::MENUNGGU)throw ValidationException::withMessages(['klaim'=>'Klaim tidak sedang menunggu persetujuan.']);if((int)$locked->created_by===$userId)throw ValidationException::withMessages(['klaim'=>'Pembuat klaim tidak boleh menyetujui klaim yang sama.']);$available=(float)DanaSosialSumber::query()->where('status','approved')->sum('saldo_tersedia');if($available<(float)$locked->nominal_diajukan)throw ValidationException::withMessages(['klaim'=>'Saldo Dana Sosial tidak mencukupi.']);$locked->update(['status'=>KlaimDanaSosial::DISETUJUI,'approved_by'=>$userId,'approved_at'=>now()]);return $locked->fresh();});}
    public function payClaim(KlaimDanaSosial $claim,array $data,int $userId):KlaimDanaSosial{return DB::transaction(function()use($claim,$data,$userId){$locked=KlaimDanaSosial::query()->lockForUpdate()->findOrFail($claim->id);if($locked->status===KlaimDanaSosial::DIBAYAR)return $locked;if($locked->status!==KlaimDanaSosial::DISETUJUI)throw ValidationException::withMessages(['klaim'=>'Klaim belum disetujui.']);$wallet=DompetKoperasi::query()->with('akun')->lockForUpdate()->findOrFail((int)$data['dompet_id']);$this->assertWallet($wallet,$data['metode_pembayaran']);$amount=(int)$locked->nominal_diajukan;if((int)$wallet->saldo<$amount)throw ValidationException::withMessages(['dompet_id'=>'Saldo Dompet tidak cukup.']);$remaining=$amount;$sources=DanaSosialSumber::query()->where('status','approved')->where('saldo_tersedia','>',0)->orderBy('tanggal')->orderBy('id')->lockForUpdate()->get();foreach($sources as $source){$allocated=min((int)$source->saldo_tersedia,$remaining);if($allocated>0){$locked->allocations()->create(['dana_sosial_sumber_id'=>$source->id,'jumlah'=>$allocated]);$source->update(['saldo_tersedia'=>(int)$source->saldo_tersedia-$allocated]);$remaining-=$allocated;}if($remaining===0)break;}if($remaining>0)throw ValidationException::withMessages(['klaim'=>'Saldo sumber Dana Sosial tidak mencukupi.']);$locked->update(['status'=>KlaimDanaSosial::DIBAYAR,'dompet_id'=>$wallet->id,'metode_pembayaran'=>$data['metode_pembayaran'],'tanggal_bayar'=>$data['tanggal_bayar'],'nomor_referensi'=>$data['nomor_referensi']??null,'paid_by'=>$userId,'paid_at'=>now()]);$this->cash->record(['idempotency_key'=>'dana-sosial:klaim:mutasi:'.$locked->id,'dompet_id'=>$wallet->id,'tipe'=>'keluar','jumlah'=>$amount,'keterangan'=>'Pembayaran klaim Dana Sosial '.$locked->kode_klaim,'referensi_tipe'=>KlaimDanaSosial::class,'referensi_id'=>$locked->id,'tanggal'=>$data['tanggal_bayar']]);$this->accounting->recordSocialClaim($locked->fresh(),$userId);return $locked->fresh(['allocations.source','dompet']);});}
    private function assertWallet(DompetKoperasi $wallet,string $method):void{$expected=$method==='tunai'?DompetKoperasi::JENIS_KAS:DompetKoperasi::JENIS_BANK;if($wallet->jenis_dompet!==$expected||!$wallet->akun)throw ValidationException::withMessages(['dompet_id'=>'Dompet tidak sesuai metode pembayaran.']);}
}
