@extends('layout.main')
@section('content')
<div class="kbsm-business-page">
 @if(session('success'))<div class="kbsm-business-alert kbsm-business-alert--success">{{ session('success') }}</div>@endif
 @if($errors->any())<div class="kbsm-business-alert kbsm-business-alert--danger"><ul>@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
 <div class="kbsm-business-header"><div><p class="kbsm-business-eyebrow">Keuangan</p><h1 class="kbsm-business-title">Dana Sosial</h1><p class="kbsm-business-subtitle">Sumber hanya alokasi SHU atau Donasi Resmi. Maker dan checker wajib memakai dua akun Admin berbeda.</p></div></div>

 <div class="kbsm-business-grid">
  <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Atur Batas Klaim</h2><p class="kbsm-business-panel__copy">Setiap perubahan membuat versi baru dengan tanggal berlaku; histori lama tidak diubah.</p></div>
   <form method="POST" action="{{ route('klaim-dana-sosial.limits.store') }}" class="kbsm-business-form">@csrf
    <div class="kbsm-business-field"><label class="kbsm-business-label">Kategori</label><select name="kategori" required class="kbsm-business-control"><option value="meninggal">Kematian</option><option value="melahirkan">Kelahiran</option><option value="khitan">Khitan</option><option value="proposal_sosial">Proposal Sosial</option></select></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Maksimal</label><input type="number" min="1" name="nominal_maksimal" required class="kbsm-business-control"></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Berlaku Mulai</label><input type="date" name="berlaku_mulai" value="{{ now()->toDateString() }}" required class="kbsm-business-control"></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Alasan/Dasar</label><textarea name="alasan" required minlength="5" maxlength="1000" class="kbsm-business-control"></textarea></div><button class="kbsm-btn kbsm-btn--navy">Simpan Versi Batas</button>
   </form>
   <div class="kbsm-business-readonly">@forelse($limits as $limit)<div><strong>{{ ucwords(str_replace('_',' ',$limit->kategori)) }}</strong> · Rp {{ number_format($limit->nominal_maksimal,0,',','.') }} · mulai {{ $limit->berlaku_mulai->format('d/m/Y') }} · {{ $limit->creator?->name ?? '-' }}</div>@empty<div>Belum ada batas klaim. Klaim belum dapat dibuat.</div>@endforelse</div>
  </section>

  <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Draft Donasi Resmi</h2><p class="kbsm-business-panel__copy">Draft belum mengubah saldo. Penerimaan baru diposting setelah Admin checker menyetujui.</p></div>
   <form method="POST" action="{{ route('klaim-dana-sosial.sources.store') }}" class="kbsm-business-form">@csrf<input type="hidden" name="jenis_sumber" value="donasi_resmi">
    <div class="kbsm-business-field"><label class="kbsm-business-label">Nama Donasi</label><input name="nama_sumber" required maxlength="150" class="kbsm-business-control"></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Metode</label><select name="metode_penerimaan" required class="kbsm-business-control"><option value="tunai">Tunai</option><option value="transfer_bank">Transfer Bank</option></select></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Dompet Penerima</label><select name="dompet_id" required class="kbsm-business-control"><option value="">Pilih Kas/Bank</option>@foreach($wallets as $wallet)<option value="{{ $wallet->id }}">{{ $wallet->nama_dompet }} · {{ strtoupper($wallet->jenis_dompet) }}</option>@endforeach</select></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Tanggal Diterima</label><input type="date" name="tanggal_diterima" value="{{ now()->toDateString() }}" required class="kbsm-business-control"></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Nominal</label><input type="number" min="1" name="nominal_awal" required class="kbsm-business-control"></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Nomor Referensi</label><input name="nomor_referensi" maxlength="100" class="kbsm-business-control"></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Referensi Bukti</label><input name="bukti_penerimaan" maxlength="255" placeholder="Nomor/path bukti penerimaan" class="kbsm-business-control"></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Keterangan</label><textarea name="keterangan" required maxlength="1000" class="kbsm-business-control"></textarea></div><button class="kbsm-btn kbsm-btn--navy">Buat Draft Donasi</button>
   </form>
  </section>

  <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Draft Klaim</h2><p class="kbsm-business-panel__copy">Nominal langsung diperiksa terhadap batas kategori yang berlaku pada tanggal pengajuan.</p></div>
   <form method="POST" action="{{ route('klaim-dana-sosial.claims.store') }}" class="kbsm-business-form">@csrf
    <div class="kbsm-business-field"><label class="kbsm-business-label">Penerima</label><select name="karyawan_id" required class="kbsm-business-control"><option value="">Pilih karyawan</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->nama }}</option>@endforeach</select></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Kategori</label><select name="kategori" required class="kbsm-business-control"><option value="meninggal">Kematian</option><option value="melahirkan">Kelahiran</option><option value="khitan">Khitan</option><option value="proposal_sosial">Proposal Sosial</option></select></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Nominal</label><input type="number" min="1" name="nominal" required class="kbsm-business-control"></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Tanggal</label><input type="date" name="tanggal_pengajuan" value="{{ now()->toDateString() }}" required class="kbsm-business-control"></div>
    <div class="kbsm-business-field"><label class="kbsm-business-label">Keterangan</label><textarea name="keterangan" required maxlength="1000" class="kbsm-business-control"></textarea></div><button class="kbsm-btn kbsm-btn--navy">Buat Draft Klaim</button>
   </form>
  </section>
 </div>

 <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Sumber, Saldo, dan Audit</h2></div><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Sumber</th><th>Dompet</th><th>Nominal/Saldo</th><th>Maker/Checker</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($sources as $source)<tr>
  <td><strong>{{ $source->kode_sumber }}</strong><div>{{ $source->nama_sumber }}</div><div class="kbsm-business-muted">{{ $source->jenis_sumber==='shu'?'Alokasi SHU':'Donasi Resmi' }} · {{ $source->tanggal_diterima?->format('d/m/Y') }}</div></td>
  <td>{{ $source->dompet?->nama_dompet ?? 'Posting SHU' }}<div class="kbsm-business-muted">{{ $source->nomor_referensi }}</div></td><td>Awal Rp {{ number_format($source->nominal_awal,0,',','.') }}<div><strong>Sisa Rp {{ number_format($source->saldo_tersedia,0,',','.') }}</strong></div></td>
  <td>Maker: {{ $source->creator?->name ?? '-' }}<div>Checker: {{ $source->approver?->name ?? '-' }}</div></td><td>{{ strtoupper($source->status) }} · {{ $source->mutations->count() }} mutasi</td><td>
   @if($source->status==='draft')<form method="POST" action="{{ route('klaim-dana-sosial.sources.approve',$source) }}" class="kbsm-business-form">@csrf<input name="approval_reason" required minlength="5" placeholder="Alasan checker" class="kbsm-business-control"><button class="kbsm-btn kbsm-btn--green kbsm-btn--sm">Setujui Donasi</button></form>@endif
   @if($source->status==='active' && $source->jenis_sumber==='donasi_resmi' && (int)$source->saldo_tersedia===(int)$source->nominal_awal)<form method="POST" action="{{ route('klaim-dana-sosial.sources.reverse',$source) }}" class="kbsm-business-form">@csrf<input name="reversal_reason" required minlength="5" placeholder="Alasan reversal" class="kbsm-business-control"><button class="kbsm-btn kbsm-btn--outline-red kbsm-btn--sm">Reversal Donasi</button></form>@endif
  </td></tr>@empty<tr><td colspan="6" class="kbsm-business-empty">Belum ada sumber Dana Sosial.</td></tr>@endforelse</tbody></table></div></section>

 <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Klaim dan Audit Pembayaran</h2></div><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Klaim</th><th>Penerima/Kategori</th><th>Nominal/Batas</th><th>Status/Sumber</th><th>Audit</th><th>Aksi</th></tr></thead><tbody>@forelse($claims as $claim)<tr>
  <td><strong>{{ $claim->kode_klaim }}</strong><div class="kbsm-business-muted">{{ $claim->tanggal_pengajuan?->format('d/m/Y') }}</div></td><td>{{ $claim->nama_penerima_snapshot }}<div>{{ ucwords(str_replace('_',' ',$claim->kategori)) }}</div><div class="kbsm-business-muted">{{ $claim->keterangan }}</div></td>
  <td><strong>Rp {{ number_format($claim->nominal,0,',','.') }}</strong><div class="kbsm-business-muted">Batas Rp {{ number_format($claim->batas_nominal_snapshot,0,',','.') }} · {{ $claim->batas_berlaku_snapshot?->format('d/m/Y') }}</div></td><td>{{ strtoupper($claim->status) }}<div>{{ $claim->sumber?->kode_sumber ?? '-' }}</div></td>
  <td>Maker: {{ $claim->creator?->name ?? '-' }}<div>Checker: {{ $claim->approver?->name ?? '-' }}</div><div>Pembayar: {{ $claim->payer?->name ?? '-' }}</div><div>Mutasi/Jurnal: {{ $claim->mutasiKas->count() }}/{{ $claim->jurnal->count() }}</div></td><td>
   @if($claim->status==='draft')<form method="POST" action="{{ route('klaim-dana-sosial.claims.submit',$claim) }}">@csrf<button class="kbsm-btn kbsm-btn--navy kbsm-btn--sm">Ajukan</button></form>@endif
   @if($claim->status==='diajukan')<form method="POST" action="{{ route('klaim-dana-sosial.claims.approve',$claim) }}" class="kbsm-business-form">@csrf<select name="sumber_dana_sosial_id" required class="kbsm-business-control"><option value="">Pilih sumber</option>@foreach($activeSources as $source)<option value="{{ $source->id }}">{{ $source->kode_sumber }} · Rp {{ number_format($source->saldo_tersedia,0,',','.') }}</option>@endforeach</select><input name="approval_reason" required minlength="5" placeholder="Alasan checker" class="kbsm-business-control"><button class="kbsm-btn kbsm-btn--green kbsm-btn--sm">Setujui</button></form><form method="POST" action="{{ route('klaim-dana-sosial.claims.reject',$claim) }}" class="kbsm-business-form">@csrf<input name="alasan_penolakan" required placeholder="Alasan" class="kbsm-business-control"><button class="kbsm-btn kbsm-btn--outline-red kbsm-btn--sm">Tolak</button></form>@endif
   @if($claim->status==='disetujui')<form method="POST" action="{{ route('klaim-dana-sosial.claims.pay',$claim) }}" class="kbsm-business-form">@csrf<select name="metode_pembayaran" class="kbsm-business-control"><option value="tunai">Tunai</option><option value="transfer_bank">Transfer Bank</option></select><select name="dompet_id" required class="kbsm-business-control"><option value="">Kas/Bank</option>@foreach($wallets as $wallet)<option value="{{ $wallet->id }}">{{ $wallet->nama_dompet }}</option>@endforeach</select><input type="date" name="tanggal_bayar" required value="{{ now()->toDateString() }}" class="kbsm-business-control"><button class="kbsm-btn kbsm-btn--green kbsm-btn--sm">Bayar</button></form>@endif
   @if($claim->status==='paid')<form method="POST" action="{{ route('klaim-dana-sosial.claims.reverse',$claim) }}" class="kbsm-business-form">@csrf<input name="reversal_reason" required minlength="5" placeholder="Alasan koreksi" class="kbsm-business-control"><button class="kbsm-btn kbsm-btn--outline-red kbsm-btn--sm">Reversal</button></form>@endif
  </td></tr>@empty<tr><td colspan="6" class="kbsm-business-empty">Belum ada klaim.</td></tr>@endforelse</tbody></table></div><div class="kbsm-business-pagination">{{ $claims->links() }}</div></section>
</div>
@endsection
