@extends('layout.main')
@section('content')
<div class="kbsm-business-page">
 @if(session('success'))<div class="kbsm-business-alert kbsm-business-alert--success">{{ session('success') }}</div>@endif
 @if($errors->any())<div class="kbsm-business-alert kbsm-business-alert--danger"><ul>@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
 <div class="kbsm-business-header"><div><p class="kbsm-business-eyebrow">Keuangan</p><h1 class="kbsm-business-title">Klaim Dana Sosial</h1><p class="kbsm-business-subtitle">Sumber, saldo, approval, pembayaran, Mutasi Kas, jurnal, dan audit dicatat terpisah.</p></div></div>
 <div class="kbsm-business-grid">
  <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Tambah Sumber Dana</h2><p class="kbsm-business-panel__copy">Sumber tambahan atau alokasi SHU closed harus disetujui sebelum saldo tersedia.</p></div><form method="POST" action="{{ route('klaim-dana-sosial.sources.store') }}" class="kbsm-business-form">@csrf
   <div class="kbsm-business-field"><label class="kbsm-business-label">Nama sumber</label><input name="nama_sumber" required class="kbsm-business-control"></div>
   <div class="kbsm-business-field"><label class="kbsm-business-label">Jenis</label><select name="jenis_sumber" required class="kbsm-business-control"><option value="tambahan_disetujui">Sumber tambahan yang disetujui</option><option value="shu">Alokasi SHU closed</option></select></div>
   <div class="kbsm-business-field"><label class="kbsm-business-label">Periode SHU (khusus sumber SHU)</label><select name="shu_koperasi_id" class="kbsm-business-control"><option value="">Tidak memakai SHU</option>@foreach($closedShu as $s)<option value="{{ $s->id }}">{{ $s->judul }} · Rp {{ number_format($s->nominal_dana_sosial,0,',','.') }}</option>@endforeach</select></div>
   <div class="kbsm-business-field"><label class="kbsm-business-label">Nominal</label><input type="number" min="1" name="nominal_awal" required class="kbsm-business-control"></div>
   <div class="kbsm-business-field"><label class="kbsm-business-label">Dasar/keterangan</label><textarea name="keterangan" class="kbsm-business-control"></textarea></div><button class="kbsm-btn kbsm-btn--navy">Buat Draft Sumber</button>
  </form></section>
  <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Buat Draft Klaim</h2></div><form method="POST" action="{{ route('klaim-dana-sosial.claims.store') }}" class="kbsm-business-form">@csrf
   <div class="kbsm-business-field"><label class="kbsm-business-label">Penerima</label><select name="karyawan_id" required class="kbsm-business-control"><option value="">Pilih karyawan</option>@foreach($employees as $e)<option value="{{ $e->id }}">{{ $e->nama }}</option>@endforeach</select></div>
   <div class="kbsm-business-field"><label class="kbsm-business-label">Kategori</label><select name="kategori" required class="kbsm-business-control"><option value="meninggal">Meninggal</option><option value="melahirkan">Melahirkan</option><option value="khitan">Khitan</option><option value="proposal_sosial">Proposal Sosial</option></select></div>
   <div class="kbsm-business-field"><label class="kbsm-business-label">Nominal</label><input type="number" min="1" name="nominal" required class="kbsm-business-control"></div><div class="kbsm-business-field"><label class="kbsm-business-label">Tanggal</label><input type="date" name="tanggal_pengajuan" value="{{ now()->toDateString() }}" required class="kbsm-business-control"></div>
   <div class="kbsm-business-field"><label class="kbsm-business-label">Keterangan</label><textarea name="keterangan" required class="kbsm-business-control"></textarea></div><button class="kbsm-btn kbsm-btn--navy">Buat Draft Klaim</button>
  </form></section>
 </div>
 <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Saldo dan Mutasi Sumber</h2></div><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Sumber</th><th>Jenis</th><th>Nominal Awal</th><th>Saldo</th><th>Status/Audit</th><th>Aksi</th></tr></thead><tbody>@forelse($sources as $s)<tr><td><strong>{{ $s->kode_sumber }}</strong><div>{{ $s->nama_sumber }}</div></td><td>{{ $s->jenis_sumber }}</td><td>Rp {{ number_format($s->nominal_awal,0,',','.') }}</td><td><strong>Rp {{ number_format($s->saldo_tersedia,0,',','.') }}</strong></td><td>{{ $s->status }} · {{ $s->mutations->count() }} mutasi</td><td>@if($s->status==='draft')<form method="POST" action="{{ route('klaim-dana-sosial.sources.approve',$s) }}">@csrf<button class="kbsm-btn kbsm-btn--green kbsm-btn--sm">Setujui Sumber</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="kbsm-business-empty">Belum ada sumber.</td></tr>@endforelse</tbody></table></div></section>
 <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Klaim dan Audit Pembayaran</h2></div><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Klaim</th><th>Penerima/Kategori</th><th>Nominal</th><th>Status/Sumber</th><th>Audit</th><th>Aksi</th></tr></thead><tbody>@forelse($claims as $c)<tr>
  <td><strong>{{ $c->kode_klaim }}</strong><div class="kbsm-business-muted">{{ $c->tanggal_pengajuan?->format('d/m/Y') }}</div></td><td>{{ $c->nama_penerima_snapshot }}<div>{{ str_replace('_',' ',$c->kategori) }}</div><div class="kbsm-business-muted">{{ $c->keterangan }}</div></td><td><strong>Rp {{ number_format($c->nominal,0,',','.') }}</strong></td><td>{{ strtoupper($c->status) }}<div>{{ $c->sumber?->kode_sumber ?? '-' }}</div></td><td><div>Pembuat: {{ $c->creator?->name }}</div><div>Approver: {{ $c->approver?->name ?? '-' }}</div><div>Pembayar: {{ $c->payer?->name ?? '-' }}</div><div>Mutasi/Jurnal: {{ $c->mutasiKas->count() }}/{{ $c->jurnal->count() }}</div></td><td>
   @if($c->status==='draft')<form method="POST" action="{{ route('klaim-dana-sosial.claims.submit',$c) }}">@csrf<button class="kbsm-btn kbsm-btn--navy kbsm-btn--sm">Ajukan</button></form>@endif
   @if($c->status==='diajukan')<form method="POST" action="{{ route('klaim-dana-sosial.claims.approve',$c) }}" class="kbsm-business-form">@csrf<select name="sumber_dana_sosial_id" required class="kbsm-business-control"><option value="">Pilih sumber</option>@foreach($activeSources as $s)<option value="{{ $s->id }}">{{ $s->kode_sumber }} · Rp {{ number_format($s->saldo_tersedia,0,',','.') }}</option>@endforeach</select><button class="kbsm-btn kbsm-btn--green kbsm-btn--sm">Setujui</button></form><form method="POST" action="{{ route('klaim-dana-sosial.claims.reject',$c) }}" class="kbsm-business-form">@csrf<input name="alasan_penolakan" required placeholder="Alasan" class="kbsm-business-control"><button class="kbsm-btn kbsm-btn--outline-red kbsm-btn--sm">Tolak</button></form>@endif
   @if($c->status==='disetujui')<form method="POST" action="{{ route('klaim-dana-sosial.claims.pay',$c) }}" class="kbsm-business-form">@csrf<select name="metode_pembayaran" class="kbsm-business-control"><option value="tunai">Tunai</option><option value="transfer_bank">Transfer Bank</option></select><select name="dompet_id" required class="kbsm-business-control"><option value="">Kas/Bank</option>@foreach($wallets as $w)<option value="{{ $w->id }}">{{ $w->nama_dompet }}</option>@endforeach</select><input type="date" name="tanggal_bayar" required value="{{ now()->toDateString() }}" class="kbsm-business-control"><button class="kbsm-btn kbsm-btn--green kbsm-btn--sm">Bayar</button></form>@endif
  </td></tr>@empty<tr><td colspan="6" class="kbsm-business-empty">Belum ada klaim.</td></tr>@endforelse</tbody></table></div><div class="kbsm-business-pagination">{{ $claims->links() }}</div></section>
</div>
@endsection
