@extends('layout.main')
@section('content')
@php $money=fn($v)=>(float)$v!=0?'Rp '.number_format((float)$v,0,',','.'):'–'; @endphp
<div class="kbsm-business-page">
 @if(session('success'))<div class="kbsm-business-alert kbsm-business-alert--success">{{ session('success') }}</div>@endif
 <header class="kbsm-business-header"><div><p class="kbsm-business-eyebrow">Akuntansi</p><h1 class="kbsm-business-title">Periode & Tutup Buku</h1><p class="kbsm-business-subtitle">Tetapkan rentang tahun buku, hitung laba resmi, buat jurnal penutup, dan kunci transaksi periode lama.</p></div><a href="{{ route('akuntansi.periode.create') }}" class="kbsm-business-add-button">Buka Periode Pembukuan</a></header>
 <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Riwayat Tutup Buku</h2><p class="kbsm-business-panel__copy">Saldo Kas dan Bank tidak direset; saldonya tetap dibawa ke periode berikutnya.</p></div><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Periode</th><th>Status</th><th class="kbsm-business-table__right">Pendapatan</th><th class="kbsm-business-table__right">Beban</th><th class="kbsm-business-table__right">Laba Bersih</th><th>Tanggal Ditutup</th><th>Aksi</th></tr></thead><tbody>@forelse($periods as $period)<tr><td><span class="kbsm-business-code">{{ $period->kode }}</span><div class="kbsm-business-muted">{{ $period->tanggal_mulai->format('d/m/Y') }}–{{ $period->tanggal_selesai->format('d/m/Y') }}</div></td><td><span class="kbsm-status {{ $period->status==='closed'?'kbsm-status--green':'kbsm-status--gold' }}">{{ $period->status_label }}</span></td><td class="kbsm-business-amount">{{ $money($period->total_pendapatan) }}</td><td class="kbsm-business-amount">{{ $money($period->total_beban) }}</td><td class="kbsm-business-amount">{{ $money($period->laba_bersih) }}</td><td>{{ $period->closed_at?->format('d/m/Y H:i') ?? '–' }}</td><td><a href="{{ route('akuntansi.periode.show',$period) }}" class="kbsm-btn kbsm-btn--outline-slate kbsm-btn--sm">{{ $period->status==='closed'?'Lihat Hasil Tutup Buku':'Detail' }}</a>@if($period->status==='open')<form method="POST" action="{{ route('akuntansi.periode.close',$period) }}" class="inline" onsubmit="return confirm('Tutup buku dan kunci seluruh tanggal pada periode ini?')">@csrf<button class="kbsm-btn kbsm-btn--navy kbsm-btn--sm">Tutup Buku</button></form>@endif</td></tr>@empty<tr><td colspan="7" class="kbsm-business-empty">Belum ada periode pembukuan. Mulai periode pertama untuk mengelola tutup buku.</td></tr>@endforelse</tbody></table></div><div class="kbsm-business-pagination">{{ $periods->links() }}</div></section>
</div>
@endsection
