@extends('layout.main')
@section('content')
@php $money = fn($value) => 'Rp ' . number_format((int) $value, 0, ',', '.'); @endphp
<div class="kbsm-business-page">
    @if(session('success'))<div class="kbsm-business-alert kbsm-business-alert--success">{{ session('success') }}</div>@endif
    <header class="kbsm-business-header"><div><p class="kbsm-business-eyebrow">Akuntansi</p><h1 class="kbsm-business-title">Periode & Tutup Buku</h1><p class="kbsm-business-subtitle">Satu periode tepat satu tahun, tanpa overlap. Periode tertutup menjadi sumber laba resmi SHU.</p></div><a href="{{ route('akuntansi.periode.create') }}" class="kbsm-business-add-button">Buka Periode</a></header>
    <section class="kbsm-business-panel"><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Periode</th><th>Status</th><th>Pendapatan</th><th>Beban</th><th>Laba Bersih</th><th>Jurnal</th><th>Ditutup</th><th>Aksi</th></tr></thead><tbody>@forelse($periods as $period)<tr><td><span class="kbsm-business-code">{{ $period->kode }}</span><div class="kbsm-business-muted">{{ $period->tanggal_mulai->format('d/m/Y') }}–{{ $period->tanggal_selesai->format('d/m/Y') }}</div></td><td><span class="kbsm-status {{ $period->status === 'closed' ? 'kbsm-status--green' : 'kbsm-status--gold' }}">{{ $period->status_label }}</span></td><td>{{ $money($period->total_pendapatan) }}</td><td>{{ $money($period->total_beban) }}</td><td>{{ $money($period->laba_bersih) }}</td><td>{{ number_format($period->jumlah_jurnal) }}</td><td>{{ $period->closed_at?->format('d/m/Y H:i') ?? '–' }}</td><td><a href="{{ route('akuntansi.periode.show', $period) }}" class="kbsm-btn kbsm-btn--outline-slate kbsm-btn--sm">Detail</a></td></tr>@empty<tr><td colspan="8" class="kbsm-business-empty">Belum ada periode pembukuan.</td></tr>@endforelse</tbody></table></div><div class="kbsm-business-pagination">{{ $periods->links() }}</div></section>
</div>
@endsection
