@extends('layout.main')
@section('content')
@php $money = fn($value) => 'Rp ' . number_format((int) $value, 0, ',', '.'); @endphp
<div class="kbsm-business-page">
    @if(session('success'))<div class="kbsm-business-alert kbsm-business-alert--success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="kbsm-business-alert kbsm-business-alert--danger"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <header class="kbsm-business-header"><div><a href="{{ route('akuntansi.periode.index') }}" class="kbsm-business-back-link">← Riwayat Tutup Buku</a><p class="kbsm-business-eyebrow">{{ $period->kode }}</p><h1 class="kbsm-business-title">{{ $period->nama }}</h1><p class="kbsm-business-subtitle">{{ $period->tanggal_mulai->format('d F Y') }}–{{ $period->tanggal_selesai->format('d F Y') }}</p></div><span class="kbsm-status {{ $period->status === 'closed' ? 'kbsm-status--green' : 'kbsm-status--gold' }}">{{ $period->status_label }}</span></header>
    <section class="kbsm-business-summary"><article class="kbsm-business-summary-card"><p class="kbsm-business-summary-label">Pendapatan</p><p class="kbsm-business-summary-value">{{ $money($period->total_pendapatan) }}</p></article><article class="kbsm-business-summary-card"><p class="kbsm-business-summary-label">Beban</p><p class="kbsm-business-summary-value">{{ $money($period->total_beban) }}</p></article><article class="kbsm-business-summary-card kbsm-business-summary-card--green"><p class="kbsm-business-summary-label">Laba Bersih</p><p class="kbsm-business-summary-value">{{ $money($period->laba_bersih) }}</p></article></section>
    @if($period->status === 'open')
        <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Edit Periode Berjalan</h2><p class="kbsm-business-panel__copy">Rentang wajib tepat satu tahun, tidak overlap, dan tidak boleh mengeluarkan jurnal yang sudah terkait.</p></div><form method="POST" action="{{ route('akuntansi.periode.update', $period) }}" class="kbsm-form-grid">@csrf @method('PATCH')<div class="kbsm-field"><label>Kode</label><input name="kode" value="{{ $period->kode }}" required></div><div class="kbsm-field"><label>Nama</label><input name="nama" value="{{ $period->nama }}" required></div><div class="kbsm-field"><label>Mulai</label><input type="date" name="tanggal_mulai" value="{{ $period->tanggal_mulai->format('Y-m-d') }}" required></div><div class="kbsm-field"><label>Selesai</label><input type="date" name="tanggal_selesai" value="{{ $period->tanggal_selesai->format('Y-m-d') }}" required></div><div class="kbsm-field kbsm-field--wide"><button class="kbsm-btn kbsm-btn--outline-slate">Simpan Perubahan</button></div></form></section>
        <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Tutup Buku</h2><p class="kbsm-business-panel__copy">Hanya jurnal posted yang dihitung. Sistem membuat jurnal penutup idempoten, snapshot, checksum, lalu mengunci periode.</p></div><form method="POST" action="{{ route('akuntansi.periode.close', $period) }}" class="kbsm-form-grid" onsubmit="return confirm('Lanjutkan tutup buku permanen?')">@csrf<div class="kbsm-field kbsm-field--wide"><label>Alasan Tutup Buku</label><textarea name="closing_reason" minlength="5" required>Penutupan tahun buku untuk perhitungan SHU dan RAT</textarea></div><div class="kbsm-field kbsm-field--wide"><button class="kbsm-btn kbsm-btn--navy">Tutup Buku</button></div></form></section>
    @else
        <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Audit Penutupan</h2><p class="kbsm-business-panel__copy">Data berikut permanen dan tidak dapat diedit.</p></div><dl class="period-audit"><div><dt>Ditutup</dt><dd>{{ $period->closed_at?->format('d/m/Y H:i') }}</dd></div><div><dt>Oleh</dt><dd>{{ $period->closer?->name ?? '–' }}</dd></div><div><dt>Alasan</dt><dd>{{ $period->closing_reason }}</dd></div><div><dt>Jurnal posted</dt><dd>{{ number_format($period->jumlah_jurnal) }}</dd></div><div><dt>Jurnal penutup</dt><dd>{{ $period->closingJournal?->nomor_bukti ?? 'Tidak diperlukan' }}</dd></div><div><dt>Checksum</dt><dd><code>{{ $period->checksum }}</code></dd></div></dl></section>
    @endif
</div>
@endsection
