@extends('layout.main')
@section('content')
<div class="coa-page">
  @if(session('success'))<div class="coa-alert coa-alert--success">{{ session('success') }}</div>@endif
  <header class="coa-page-header"><div><p class="coa-eyebrow">Akuntansi</p><h1 class="coa-page-title">Daftar Akun Keuangan</h1><p class="coa-page-subtitle">Kelola akun yang menjadi sumber pencatatan jurnal dan laporan koperasi.</p></div><a href="{{ route('akun.create') }}" class="coa-btn coa-btn--primary">+ Tambah Akun</a></header>
  <section class="coa-data-panel"><div class="coa-data-header"><div><h2 class="coa-section-title">Daftar Akun</h2><p class="coa-section-copy">Akun sistem dan akun yang sudah dipakai jurnal memiliki identitas inti yang dilindungi.</p></div><span class="coa-result-count">{{ $akun->total() }} akun</span></div>
    <div class="coa-filter-bar"><form method="GET" class="coa-filter-grid coa-filter-grid--status"><div class="coa-field"><label class="coa-label">Kode atau Nama</label><input class="coa-input" name="search" value="{{ $search }}" placeholder="Cari akun"></div><div class="coa-field"><label class="coa-label">Kategori</label><select class="coa-input" name="kategori"><option value="">Semua kategori</option>@foreach($categories as $key=>$label)<option value="{{ $key }}" @selected($kategori===$key)>{{ $label }}</option>@endforeach</select></div><div class="coa-field"><label class="coa-label">Status</label><select class="coa-input" name="status"><option value="">Semua status</option><option value="aktif" @selected($status==='aktif')>Aktif</option><option value="nonaktif" @selected($status==='nonaktif')>Nonaktif</option></select></div><div class="coa-filter-actions"><button class="coa-btn coa-btn--navy">Tampilkan</button><a href="{{ route('akun.index') }}" class="coa-btn coa-btn--secondary">Reset</a></div></form></div>
    <div class="coa-table-wrap"><table class="coa-table"><thead><tr><th>Kode</th><th>Nama Akun</th><th>Kategori</th><th>Saldo Normal</th><th>Bisa untuk Beban Operasional</th><th>Status/Penggunaan</th><th>Aksi</th></tr></thead><tbody>@forelse($akun as $item)<tr><td><span class="coa-code">{{ $item->kode_akun }}</span></td><td><span class="coa-account-name">{{ $item->nama_akun }}</span><span class="coa-description">{{ $item->keterangan ?: '–' }}</span></td><td><span class="coa-badge coa-badge--{{ $item->kategori }}">{{ $item->kategori_label }}</span></td><td>{{ ucfirst($item->posisi_saldo) }}</td><td>{{ $item->is_beban_operasional ? 'Ya' : 'Tidak' }}</td><td><span class="coa-badge {{ $item->is_aktif?'coa-badge--debit':'coa-badge--tambahan' }}">{{ $item->is_aktif?'Aktif':'Nonaktif' }}</span><span class="coa-description">{{ $item->is_sistem?'Akun sistem':($item->jurnalDetails()->exists()?'Sudah digunakan jurnal':'Belum digunakan') }}</span></td><td><a href="{{ route('akun.edit',$item) }}" class="coa-btn coa-btn--secondary">Edit</a></td></tr>@empty<tr><td colspan="7"><div class="coa-empty-state"><h3>Belum ada akun yang cocok.</h3><p>Ubah filter atau tambahkan akun baru.</p></div></td></tr>@endforelse</tbody></table></div>
    <div class="coa-pagination-wrap">{{ $akun->links() }}</div>
  </section>
</div>
@endsection
