<?php

return [
    'brand' => [
        'name' => 'KBSM',
        'subtitle' => 'POS, Simpan Pinjam, dan Laporan',
        'logo' => 'assets/img/logo-koperasi.png',
    ],

    'quick_links' => [
        'pages.dashboard',
        'waserba.index',
        'produk.index',
        'simpanan.index',
        'pinjaman.index',
        'periode-potong-gaji.index',
    ],

    'modules' => [
        [
            'section' => 'Dashboard',
            'label' => 'Dashboard',
            'route' => 'pages.dashboard',
            'roles' => ['kasir', 'admin'],
            'patterns' => ['pages.dashboard'],
            'paths' => ['/', 'dashboard'],
            'description' => 'Pantau omzet, transaksi, dan ringkasan performa koperasi.',
            'keywords' => ['beranda', 'home', 'ringkasan', 'statistik'],
        ],
        [
            'section' => 'POS Koperasi',
            'label' => 'Penjualan / Kasir',
            'route' => 'waserba.index',
            'roles' => ['kasir'],
            'patterns' => ['waserba.*'],
            'description' => 'Kelola transaksi kasir, checkout, dan pencatatan penjualan.',
            'keywords' => ['kasir', 'checkout', 'struk', 'penjualan toko'],
        ],
        [
            'section' => 'POS Koperasi',
            'label' => 'Kategori Produk',
            'route' => 'kategori-produk.index',
            'roles' => ['admin'],
            'patterns' => ['kategori-produk.*'],
            'description' => 'Atur kategori agar produk lebih rapi dan mudah dicari.',
            'keywords' => ['kategori', 'kelompok produk', 'jenis barang'],
        ],
        [
            'section' => 'POS Koperasi',
            'label' => 'Produk',
            'route' => 'produk.index',
            'roles' => ['admin'],
            'patterns' => ['produk.*'],
            'description' => 'Kelola data barang, harga, dan stok produk koperasi.',
            'keywords' => ['barang', 'stok', 'item', 'inventaris'],
        ],
        [
            'section' => 'POS Koperasi',
            'label' => 'Reseller',
            'route' => 'reseller.index',
            'roles' => ['admin'],
            'patterns' => ['reseller.*'],
            'description' => 'Kelola mitra reseller dan data konsinyasi barang titipan.',
            'keywords' => ['konsinyasi', 'titip jual', 'mitra'],
        ],
        [
            'section' => 'POS Koperasi',
            'label' => 'Pembayaran Konsinyasi',
            'route' => 'pembayaran-konsinyasi.index',
            'roles' => ['admin'],
            'patterns' => ['pembayaran-konsinyasi.*'],
            'description' => 'Bayarkan hasil penjualan konsinyasi ke reseller dan catat mutasi kas.',
            'keywords' => ['bayar reseller', 'hutang reseller', 'setor konsinyasi'],
        ],
        [
            'section' => 'Master Data',
            'label' => 'Karyawan',
            'route' => 'karyawan.index',
            'roles' => ['admin'],
            'patterns' => ['karyawan.*'],
            'description' => 'Kelola identitas dan status kerja karyawan perusahaan.',
            'keywords' => ['karyawan', 'pegawai', 'status kerja'],
        ],
        [
            'section' => 'Master Data',
            'label' => 'Anggota',
            'route' => 'anggota.index',
            'roles' => ['admin'],
            'patterns' => ['anggota.*'],
            'description' => 'Kelola keanggotaan koperasi yang terhubung ke Karyawan.',
            'keywords' => ['anggota', 'nomor anggota', 'member', 'plafon'],
        ],

        [
            'section' => 'Master Data',
            'label' => 'Pengurus',
            'route' => 'pengurus-koperasi.index',
            'roles' => ['admin'],
            'patterns' => ['pengurus-koperasi.*'],
            'description' => 'Kelola data pengurus untuk struktur organisasi koperasi.',
            'keywords' => ['pengurus', 'manajemen', 'pengelola'],
        ],

        [
            'section' => 'Master Data',
            'label' => 'COA',
            'route' => 'akun.index',
            'roles' => ['admin'],
            'patterns' => ['akun.*'],
            'description' => 'Kelola daftar akun sebagai sumber pencatatan jurnal koperasi.',
            'keywords' => ['coa', 'chart of accounts', 'kode akun', 'master akun'],
        ],

        [
            'section' => 'Master Data',
            'label' => 'Printer Koperasi',
            'route' => 'aset-printer.index',
            'roles' => ['admin'],
            'feature' => 'master_printer_enabled',
            'patterns' => ['aset-printer.*'],
            'description' => 'Kelola master aset printer koperasi.',
            'keywords' => ['printer', 'aset printer', 'perangkat koperasi'],
        ],
        [
            'section' => 'Kas & Bank',
            'label' => 'Dompet Koperasi',
            'route' => 'dompet-koperasi.index',
            'roles' => ['admin'],
            'patterns' => ['dompet-koperasi.*'],
            'description' => 'Kelola saldo kas, bank, dan dompet operasional lintas modul koperasi.',
            'keywords' => ['kas', 'bank', 'saldo', 'dompet', 'rekening internal'],
        ],
        [
            'section' => 'Kas & Bank',
            'label' => 'Mutasi Kas & Bank',
            'route' => 'mutasi-kas.index',
            'roles' => ['admin'],
            'patterns' => ['mutasi-kas.*'],
            'description' => 'Monitor arus keluar masuk kas dan bank dari transaksi resmi.',
            'keywords' => ['arus kas', 'cash flow', 'mutasi', 'bank'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Transaksi Simpanan',
            'route' => 'simpanan.index',
            'roles' => ['admin'],
            'patterns' => ['simpanan.*'],
            'description' => 'Catat setoran dan transaksi simpanan anggota.',
            'keywords' => ['setoran', 'tabungan anggota', 'transaksi simpanan'],
        ],

        [
            'section' => 'Simpan Pinjam',
            'label' => 'Pinjaman',
            'route' => 'pinjaman.index',
            'roles' => ['admin'],
            'patterns' => ['pinjaman.*'],
            'description' => 'Kelola pengajuan dan transaksi pinjaman anggota.',
            'keywords' => ['peminjaman', 'pengajuan pinjaman'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Cicilan Pinjaman',
            'route' => 'cicilan-pinjaman.index',
            'roles' => ['admin'],
            'patterns' => ['cicilan-pinjaman.*'],
            'description' => 'Catat pembayaran angsuran dan cicilan pinjaman.',
            'keywords' => ['angsuran', 'bayar cicilan', 'pelunasan'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Periode Potong Gaji',
            'route' => 'periode-potong-gaji.index',
            'roles' => ['admin'],
            'patterns' => ['periode-potong-gaji.*'],
            'description' => 'Kelola limit bulanan, reservasi cicilan, dan konfirmasi payroll per Anggota.',
            'keywords' => ['payroll', 'potong gaji', 'limit bulanan', 'reservasi cicilan'],
        ],
        [
            'section' => 'Usaha Koperasi',
            'label' => 'Sewa Mobil',
            'route' => 'sewa-mobil.finance.index',
            'roles' => ['admin'],
            'patterns' => ['sewa-mobil.finance.*'],
            'description' => 'Kelola transaksi sewa mobil koperasi.',
            'keywords' => ['sewa mobil', 'rental mobil', 'usaha koperasi'],
        ],
        [
            'section' => 'Usaha Koperasi',
            'label' => 'Sewa Hardware',
            'route' => 'sewa-printer.index',
            'roles' => ['admin'],
            'patterns' => ['sewa-printer.*'],
            'description' => 'Kelola transaksi Sewa Hardware vendor-based.',
            'keywords' => ['sewa hardware', 'printer', 'laptop', 'kamera', 'usaha koperasi'],
        ],
        [
            'section' => 'Usaha Koperasi',
            'label' => 'Invoice Perusahaan',
            'route' => 'invoice-penagihan.index',
            'roles' => ['admin'],
            'patterns' => ['invoice-penagihan.*'],
            'description' => 'Kelola tagihan B2B BEE, BBS, dan BKM serta pembayaran parsial.',
            'keywords' => ['invoice', 'piutang perusahaan', 'b2b'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Klaim Dana Sosial',
            'route' => 'klaim-dana-sosial.index',
            'roles' => ['admin'],
            'patterns' => ['klaim-dana-sosial.*'],
            'description' => 'Kelola sumber, approval, pembayaran, dan audit Dana Sosial.',
            'keywords' => ['dana sosial', 'klaim', 'meninggal', 'melahirkan', 'khitan'],
        ],
        [
            'section' => 'Operasional',
            'label' => 'Beban Operasional',
            'route' => 'beban-operasional.index',
            'roles' => ['admin'],
            'patterns' => ['beban-operasional.*'],
            'description' => 'Catat, posting, dan audit beban operasional koperasi.',
            'keywords' => ['beban', 'biaya', 'operasional', 'expense'],
        ],
        [
            'section' => 'SHU Koperasi',
            'label' => 'Transaksi SHU',
            'route' => 'shu-koperasi.index',
            'roles' => ['admin'],
            'feature' => 'shu_enabled',
            'patterns' => ['shu-koperasi.*'],
            'description' => 'Kelola perhitungan dan transaksi Sisa Hasil Usaha.',
            'keywords' => ['shu', 'sisa hasil usaha', 'bagi hasil'],
        ],
        [
            'section' => 'Laporan Akuntansi',
            'label' => 'Laporan Potong Gaji',
            'route' => 'laporan.potong-gaji',
            'roles' => ['admin'],
            'patterns' => ['laporan.potong-gaji'],
            'description' => 'Lihat rekap potong gaji anggota atau karyawan.',
            'keywords' => ['gaji', 'laporan gaji', 'potongan'],
        ],
        [
            'section' => 'Laporan Akuntansi',
            'label' => 'Jurnal Umum Periodik',
            'route' => 'akuntansi.jurnal-umum',
            'roles' => ['admin'],
            'patterns' => ['akuntansi.jurnal-umum'],
            'description' => 'Catat transaksi secara kronologis per periode.',
            'keywords' => ['jurnal umum', 'akuntansi', 'transaksi'],
        ],
        [
            'section' => 'Laporan Akuntansi',
            'label' => 'Buku Besar',
            'route' => 'akuntansi.buku-besar',
            'roles' => ['admin'],
            'patterns' => ['akuntansi.buku-besar'],
            'description' => 'Lihat saldo per akun dari jurnal umum.',
            'keywords' => ['ledger', 'akun', 'saldo', 'buku besar'],
        ],
        [
            'section' => 'Laporan Operasional',
            'label' => 'Laporan Konsinyasi',
            'route' => 'konsinyasi.report',
            'roles' => ['admin'],
            'patterns' => ['konsinyasi.report'],
            'description' => 'Pantau performa penjualan konsinyasi dan reseller.',
            'keywords' => ['laporan reseller', 'konsinyasi', 'titipan'],
        ],
    ],
];
