<?php

return [
    'brand' => [
        'name' => 'Koperasi BITA',
        'subtitle' => 'POS, Simpan Pinjam, dan Laporan',
        'logo' => 'assets/img/logo-koperasi.png',
    ],

    'quick_links' => [
        'pages.dashboard',
        'penjualan.index',
        'produk.index',
        'simpanan.index',
        'pinjaman.index',
        'shu-koperasi.index',
    ],

    'modules' => [
        [
            'section' => 'Dashboard',
            'label' => 'Dashboard',
            'route' => 'pages.dashboard',
            'patterns' => ['pages.dashboard'],
            'paths' => ['/', 'dashboard'],
            'description' => 'Pantau omzet, transaksi, dan ringkasan performa koperasi.',
            'keywords' => ['beranda', 'home', 'ringkasan', 'statistik'],
        ],
        [
            'section' => 'POS Koperasi',
            'label' => 'Penjualan / Kasir',
            'route' => 'penjualan.index',
            'patterns' => ['penjualan.*'],
            'description' => 'Kelola transaksi kasir, checkout, dan pencatatan penjualan.',
            'keywords' => ['kasir', 'checkout', 'struk', 'penjualan toko'],
        ],
        [
            'section' => 'POS Koperasi',
            'label' => 'Kategori Produk',
            'route' => 'kategori-produk.index',
            'patterns' => ['kategori-produk.*'],
            'description' => 'Atur kategori agar produk lebih rapi dan mudah dicari.',
            'keywords' => ['kategori', 'kelompok produk', 'jenis barang'],
        ],
        [
            'section' => 'POS Koperasi',
            'label' => 'Produk',
            'route' => 'produk.index',
            'patterns' => ['produk.*'],
            'description' => 'Kelola data barang, harga, dan stok produk koperasi.',
            'keywords' => ['barang', 'stok', 'item', 'inventaris'],
        ],
        [
            'section' => 'POS Koperasi',
            'label' => 'Reseller',
            'route' => 'reseller.index',
            'patterns' => ['reseller.*'],
            'description' => 'Kelola mitra reseller dan data konsinyasi barang titipan.',
            'keywords' => ['konsinyasi', 'titip jual', 'mitra'],
        ],
        [
            'section' => 'POS Koperasi',
            'label' => 'Pembayaran Konsinyasi',
            'route' => 'pembayaran-konsinyasi.index',
            'patterns' => ['pembayaran-konsinyasi.*'],
            'description' => 'Bayarkan hasil penjualan konsinyasi ke reseller dan catat mutasi kas.',
            'keywords' => ['bayar reseller', 'hutang reseller', 'setor konsinyasi'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Karyawan / Anggota',
            'route' => 'karyawan.index',
            'patterns' => ['karyawan.*'],
            'description' => 'Kelola data anggota atau karyawan koperasi.',
            'keywords' => ['anggota', 'pegawai', 'member'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Jenis Simpanan',
            'route' => 'jenis-simpanan.index',
            'patterns' => ['jenis-simpanan.*'],
            'description' => 'Atur tipe simpanan seperti pokok, wajib, dan sukarela.',
            'keywords' => ['tabungan', 'simpanan wajib', 'simpanan pokok'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Pengurus Koperasi',
            'route' => 'pengurus-koperasi.index',
            'patterns' => ['pengurus-koperasi.*'],
            'description' => 'Kelola data pengurus untuk struktur organisasi koperasi.',
            'keywords' => ['pengurus', 'manajemen', 'pengelola'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Jenis Pinjaman',
            'route' => 'jenis-pinjaman.index',
            'patterns' => ['jenis-pinjaman.*'],
            'description' => 'Atur jenis pinjaman beserta skema dan ketentuannya.',
            'keywords' => ['skema pinjaman', 'kategori pinjaman'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Dompet Koperasi',
            'route' => 'dompet-koperasi.index',
            'patterns' => ['dompet-koperasi.*'],
            'description' => 'Pantau saldo kas dan dompet operasional koperasi.',
            'keywords' => ['kas', 'saldo', 'dompet', 'rekening internal'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Transaksi Simpanan',
            'route' => 'simpanan.index',
            'patterns' => ['simpanan.*'],
            'description' => 'Catat setoran dan transaksi simpanan anggota.',
            'keywords' => ['setoran', 'tabungan anggota', 'transaksi simpanan'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Pinjaman',
            'route' => 'pinjaman.index',
            'patterns' => ['pinjaman.*'],
            'description' => 'Kelola pengajuan dan transaksi pinjaman anggota.',
            'keywords' => ['peminjaman', 'pengajuan pinjaman'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Cicilan Pinjaman',
            'route' => 'cicilan-pinjaman.index',
            'patterns' => ['cicilan-pinjaman.*'],
            'description' => 'Catat pembayaran angsuran dan cicilan pinjaman.',
            'keywords' => ['angsuran', 'bayar cicilan', 'pelunasan'],
        ],
        [
            'section' => 'Simpan Pinjam',
            'label' => 'Mutasi Kas',
            'route' => 'mutasi-kas.index',
            'patterns' => ['mutasi-kas.*'],
            'description' => 'Monitor arus keluar masuk kas koperasi.',
            'keywords' => ['arus kas', 'cash flow', 'mutasi'],
        ],
        [
            'section' => 'SHU Koperasi',
            'label' => 'Transaksi SHU',
            'route' => 'shu-koperasi.index',
            'patterns' => ['shu-koperasi.*'],
            'description' => 'Kelola perhitungan dan transaksi Sisa Hasil Usaha.',
            'keywords' => ['shu', 'sisa hasil usaha', 'bagi hasil'],
        ],
        [
            'section' => 'Laporan',
            'label' => 'Laporan Potong Gaji',
            'route' => 'laporan.potong-gaji',
            'patterns' => ['laporan.potong-gaji'],
            'description' => 'Lihat rekap potong gaji anggota atau karyawan.',
            'keywords' => ['gaji', 'laporan gaji', 'potongan'],
        ],
        [
            'section' => 'Laporan',
            'label' => 'Laporan Konsinyasi',
            'route' => 'konsinyasi.report',
            'patterns' => ['konsinyasi.report'],
            'description' => 'Pantau performa penjualan konsinyasi dan reseller.',
            'keywords' => ['laporan reseller', 'konsinyasi', 'titipan'],
        ],
    ],
];
