@extends('layout.main')
@section('content')
@php $money = fn($value) => 'Rp ' . number_format((float) $value, 0, ',', '.'); @endphp
<div class="kbsm-business-page invoice-page">
  <header class="kbsm-business-header"><div><a href="{{ route('invoice-penagihan.index') }}" class="kbsm-business-back-link">← Daftar Invoice</a><p class="kbsm-business-eyebrow">Usaha Koperasi</p><h1 class="kbsm-business-title">Buat Invoice Perusahaan</h1><p class="kbsm-business-subtitle">Pilih kontrak yang akan digabung dalam satu invoice perusahaan.</p></div></header>
  @if($errors->any())<div class="kbsm-business-alert kbsm-business-alert--danger"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
  <section class="kbsm-business-panel">
    <form method="GET" action="{{ route('invoice-penagihan.create') }}" class="invoice-company-picker"><div class="kbsm-business-field"><label class="kbsm-business-label">Perusahaan</label><select class="kbsm-business-control" name="perusahaan_id" required><option value="">Pilih perusahaan</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected($companyId == $company->id)>{{ $company->kode }} — {{ $company->nama }}</option>@endforeach</select></div><button class="kbsm-btn kbsm-btn--outline-slate">Tampilkan Kontrak</button></form>
  </section>
  @if($companyId)
  <form method="POST" action="{{ route('invoice-penagihan.store') }}" data-invoice-selection>@csrf<input type="hidden" name="perusahaan_id" value="{{ $companyId }}">
    <section class="kbsm-business-panel"><div class="kbsm-business-grid"><div class="kbsm-business-field"><label class="kbsm-business-label">Tanggal Invoice</label><input class="kbsm-business-control" type="date" name="tanggal_invoice" value="{{ old('tanggal_invoice', today()->toDateString()) }}" required></div><div class="kbsm-business-field"><label class="kbsm-business-label">Jatuh Tempo</label><input class="kbsm-business-control" type="date" name="jatuh_tempo" value="{{ old('jatuh_tempo', today()->addDays(14)->toDateString()) }}" required></div></div></section>
    <section class="kbsm-business-panel"><div class="invoice-selection-header"><div><h2 class="kbsm-business-panel__title">Kontrak Siap Ditagihkan</h2><p class="kbsm-business-panel__copy"><span data-selected-count>0</span> kontrak dipilih · total <span data-selected-total>Rp 0</span></p></div><div><button type="button" class="kbsm-btn kbsm-btn--outline-slate kbsm-btn--sm" data-select-all>Pilih Semua</button><button type="button" class="kbsm-btn kbsm-btn--outline-slate kbsm-btn--sm" data-clear-all>Kosongkan Pilihan</button></div></div>
      <h3 class="invoice-selection-title">Sewa Mobil Siap Ditagihkan</h3><div class="invoice-choice-grid">@forelse($mobil as $item)<label class="invoice-choice"><input type="checkbox" name="sewa_mobil_ids[]" value="{{ $item->id }}" data-amount="{{ (int)$item->total_tagihan_perusahaan }}"><span class="invoice-choice__check">✓</span><span><strong>{{ $item->kode_sewa }}</strong><small>{{ $item->karyawan->nama }} · {{ $item->vehicle_label }}</small><em>{{ $money($item->total_tagihan_perusahaan) }}</em></span></label>@empty<p class="kbsm-business-empty">Tidak ada Sewa Mobil yang siap ditagihkan.</p>@endforelse</div>
      <h3 class="invoice-selection-title">Sewa Hardware Siap Ditagihkan</h3><div class="invoice-choice-grid">@forelse($hardware as $item)<label class="invoice-choice"><input type="checkbox" name="sewa_hardware_ids[]" value="{{ $item->id }}" data-amount="{{ (int)$item->total_tagihan_perusahaan }}"><span class="invoice-choice__check">✓</span><span><strong>{{ $item->kode_sewa }}</strong><small>{{ $item->karyawan->nama }} · {{ $item->mulai_tanggal->format('d/m/Y') }}–{{ $item->selesai_tanggal->format('d/m/Y') }}</small><em>{{ $money($item->total_tagihan_perusahaan) }}</em></span></label>@empty<p class="kbsm-business-empty">Tidak ada Sewa Hardware yang siap ditagihkan.</p>@endforelse</div>
      <div class="kbsm-business-actions"><a href="{{ route('invoice-penagihan.index') }}" class="kbsm-btn kbsm-btn--outline-slate">Batal</a><button class="kbsm-btn kbsm-btn--navy" data-submit-invoice disabled>Buat Invoice</button></div>
    </section>
  </form>
  @endif
</div>
<script>
document.addEventListener('DOMContentLoaded',()=>{const form=document.querySelector('[data-invoice-selection]');if(!form)return;const boxes=[...form.querySelectorAll('input[type=checkbox][data-amount]')],count=form.querySelector('[data-selected-count]'),total=form.querySelector('[data-selected-total]'),submit=form.querySelector('[data-submit-invoice]');const refresh=()=>{const selected=boxes.filter(b=>b.checked);count.textContent=selected.length;total.textContent=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(selected.reduce((sum,b)=>sum+Number(b.dataset.amount),0));submit.disabled=selected.length===0;boxes.forEach(b=>b.closest('.invoice-choice').classList.toggle('is-selected',b.checked));};boxes.forEach(b=>b.addEventListener('change',refresh));form.querySelector('[data-select-all]').addEventListener('click',()=>{boxes.forEach(b=>b.checked=true);refresh();});form.querySelector('[data-clear-all]').addEventListener('click',()=>{boxes.forEach(b=>b.checked=false);refresh();});refresh();});
</script>
@endsection
