@extends('layout.main')
@section('content')
@php $money = fn($value) => (float)$value > 0 ? 'Rp '.number_format((float)$value,0,',','.') : '–'; @endphp
<div class="kbsm-business-page invoice-page">
  @if(session('success'))<div class="kbsm-business-alert kbsm-business-alert--success">{{ session('success') }}</div>@endif
  @if($errors->any())<div class="kbsm-business-alert kbsm-business-alert--danger"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
  <header class="kbsm-business-header"><div><a href="{{ route('invoice-penagihan.index') }}" class="kbsm-business-back-link">← Daftar Invoice</a><p class="kbsm-business-eyebrow">{{ $invoice->perusahaan->kode }} · Invoice Perusahaan</p><h1 class="kbsm-business-title">{{ $invoice->nomor_invoice }}</h1><p class="kbsm-business-subtitle">Dibuat {{ $invoice->tanggal_invoice->format('d/m/Y') }} · jatuh tempo {{ $invoice->jatuh_tempo->format('d/m/Y') }}</p></div><span class="kbsm-status {{ $invoice->status==='paid'?'kbsm-status--green':'kbsm-status--gold' }}">{{ $invoice->status_label }}</span></header>
  <section class="kbsm-business-summary invoice-detail-summary"><article class="kbsm-business-summary-card"><p class="kbsm-business-summary-label">Total Tagihan</p><p class="kbsm-business-summary-value">{{ $money($invoice->total_tagihan) }}</p></article><article class="kbsm-business-summary-card kbsm-business-summary-card--green"><p class="kbsm-business-summary-label">Sudah Dibayar</p><p class="kbsm-business-summary-value">{{ $money($invoice->total_dibayar) }}</p></article><article class="kbsm-business-summary-card kbsm-business-summary-card--gold"><p class="kbsm-business-summary-label">Sisa Utang</p><p class="kbsm-business-summary-value">{{ $money($invoice->sisa_tagihan) }}</p></article></section>
  @if((float)$invoice->sisa_tagihan>0)<section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Catat Pembayaran</h2><p class="kbsm-business-panel__copy">Jumlah tidak boleh melebihi sisa utang.</p></div><form method="POST" action="{{ route('invoice-penagihan.pembayaran.store',$invoice) }}" class="invoice-payment-form">@csrf<div class="kbsm-business-field"><label class="kbsm-business-label">Jumlah Pembayaran</label><input class="kbsm-business-control" type="number" name="jumlah" min="1" max="{{ (int)$invoice->sisa_tagihan }}" required></div><div class="kbsm-business-field"><label class="kbsm-business-label">Metode</label><select class="kbsm-business-control" name="metode"><option value="tunai">Tunai</option><option value="transfer_bank">Bank</option></select></div><div class="kbsm-business-field"><label class="kbsm-business-label">Dompet Penerimaan</label><select class="kbsm-business-control" name="dompet_id" required><option value="">Pilih Dompet</option>@foreach($wallets as $wallet)<option value="{{ $wallet->id }}">{{ $wallet->nama_dompet }} ({{ $wallet->jenis_dompet }})</option>@endforeach</select></div><div class="kbsm-business-field"><label class="kbsm-business-label">Tanggal</label><input class="kbsm-business-control" type="date" name="tanggal_bayar" value="{{ today()->toDateString() }}" required></div><div class="kbsm-business-field"><label class="kbsm-business-label">Nomor Referensi <span>opsional</span></label><input class="kbsm-business-control" name="nomor_referensi"></div><button class="kbsm-btn kbsm-btn--navy">Simpan Pembayaran</button></form></section>@endif
  <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Rincian Kontrak</h2></div><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Kontrak</th><th>Jenis</th><th>Deskripsi</th><th class="kbsm-business-table__right">Tagihan</th><th class="kbsm-business-table__right">Terbayar</th><th>Status</th></tr></thead><tbody>@foreach($invoice->detail as $detail)<tr><td class="kbsm-business-code">{{ $detail->referensi->kode_sewa ?? '–' }}</td><td>{{ $detail->referensi_type===\App\Models\SewaMobil::class?'Sewa Mobil':'Sewa Hardware' }}</td><td>{{ $detail->deskripsi }}</td><td class="kbsm-business-amount">{{ $money($detail->nominal) }}</td><td class="kbsm-business-amount">{{ $money($detail->allocations->sum('jumlah')) }}</td><td>{{ $detail->status==='aktif'?'Aktif':'Dana Dikembalikan' }}</td></tr>@endforeach</tbody></table></div></section>
  <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Histori Pembayaran</h2></div><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Tanggal</th><th>Metode</th><th>Dompet</th><th>Referensi</th><th>Diproses Oleh</th><th class="kbsm-business-table__right">Jumlah</th></tr></thead><tbody>@forelse($invoice->pembayaran as $payment)<tr><td>{{ $payment->tanggal_bayar->format('d/m/Y') }}</td><td>{{ $payment->metode==='tunai'?'Tunai':'Bank' }}</td><td>{{ $payment->dompet->nama_dompet }}</td><td>{{ $payment->nomor_referensi ?: '–' }}</td><td>{{ $payment->creator->name }}</td><td class="kbsm-business-amount">{{ $money($payment->jumlah) }}</td></tr>@empty<tr><td colspan="6" class="kbsm-business-empty">Belum ada pembayaran.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
