@extends('layout.main')
@section('content')
@php $money = fn($value) => 'Rp ' . number_format((int) $value, 0, ',', '.'); @endphp
<div class="kbsm-business-page">
    @if(session('success'))<div class="kbsm-business-alert kbsm-business-alert--success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="kbsm-business-alert kbsm-business-alert--danger">{{ $errors->first() }}</div>@endif
    <header class="kbsm-business-header"><div><p class="kbsm-business-eyebrow">SHU & Dana Sosial</p><h1 class="kbsm-business-title">Pembagian SHU Tahunan</h1><p class="kbsm-business-subtitle">Laba resmi berasal dari periode tertutup; satu periode hanya dapat memiliki satu SHU.</p></div><div class="kbsm-business-actions"><a href="{{ route('struktur-koperasi.index') }}" class="kbsm-btn kbsm-btn--outline-slate">Struktur Koperasi</a><a href="{{ route('shu-config.index') }}" class="kbsm-btn kbsm-btn--outline-slate">Pengaturan SHU</a></div></header>
    <div class="kbsm-business-metrics"><article><span>Total Periode SHU</span><strong>{{ number_format($summary['periods']) }}</strong></article><article><span>Sudah Disetujui</span><strong>{{ number_format($summary['approved']) }}</strong></article><article><span>Total SHU Disetujui</span><strong>{{ $money($summary['total_shu']) }}</strong></article><article><span>Hak Belum Dibayar</span><strong>{{ $money($summary['unpaid']) }}</strong></article></div>
    <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Terapkan Periode</h2><p class="kbsm-business-panel__copy">Membuat Rancangan berdasarkan konfigurasi efektif, Wajib, Manasuka, penjualan final, dan Struktur Koperasi pada akhir periode.</p></div><form method="POST" action="{{ route('shu-koperasi.store') }}" class="kbsm-form-grid">@csrf<div class="kbsm-field"><label>Periode Tertutup</label><select name="periode_id" required><option value="">Pilih periode</option>@foreach($availablePeriods as $period)<option value="{{ $period->id }}">{{ $period->kode }} · {{ $period->nama }} · laba {{ $money($period->laba_bersih) }}</option>@endforeach</select></div><div class="kbsm-field"><button class="kbsm-btn kbsm-btn--navy" {{ $availablePeriods->isEmpty() ? 'disabled' : '' }}>Buat Rancangan</button></div></form>@if($availablePeriods->isEmpty())<div class="kbsm-business-empty">Tidak ada periode tertutup yang belum mempunyai SHU.</div>@endif</section>
    <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Riwayat Pembagian</h2></div><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Tahun Buku</th><th>Laba Resmi</th><th>Status</th><th>Disetujui</th><th>Belum Dibayar</th><th>Aksi</th></tr></thead><tbody>@forelse($processes as $shu)<tr><td><span class="kbsm-business-code">{{ $shu->periode?->kode }}</span><div class="kbsm-business-muted">{{ $shu->tanggal_mulai->format('d/m/Y') }}–{{ $shu->tanggal_selesai->format('d/m/Y') }}</div></td><td>{{ $money($shu->shu_total) }}</td><td><span class="kbsm-status {{ $shu->status === 'approved' ? 'kbsm-status--green' : 'kbsm-status--gold' }}">{{ $shu->status_label }}</span></td><td>{{ $shu->approved_at?->format('d/m/Y H:i') ?? '–' }}</td><td>{{ $money($shu->total_belum_dibayar) }}</td><td><a class="kbsm-btn kbsm-btn--outline-slate kbsm-btn--sm" href="{{ route('shu-koperasi.show', $shu) }}">Detail</a></td></tr>@empty<tr><td colspan="6" class="kbsm-business-empty">Belum ada pembagian SHU.</td></tr>@endforelse</tbody></table></div><div class="kbsm-business-pagination">{{ $processes->links() }}</div></section>
</div>
@endsection
