@extends('layout.main')
@section('content')
<div class="kbsm-business-page">
 @if(session('success'))<div class="kbsm-business-alert kbsm-business-alert--success">{{ session('success') }}</div>@endif
 @if($errors->any())<div class="kbsm-business-alert kbsm-business-alert--danger"><ul>@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
 <div class="kbsm-business-header"><div><p class="kbsm-business-eyebrow">SHU · {{ strtoupper($shuKoperasi->status) }}</p><h1 class="kbsm-business-title">{{ $shuKoperasi->judul }}</h1><p class="kbsm-business-subtitle">Snapshot periode {{ $shuKoperasi->periodeAkuntansi?->kode }} · checksum {{ substr($shuKoperasi->source_snapshot['checksum'] ?? '-',0,16) }}</p></div><a href="{{ route('shu-koperasi.index') }}" class="kbsm-btn kbsm-btn--outline">Kembali</a></div>
 <div class="kbsm-business-grid">
  <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Sumber Laba Terkunci</h2></div><div class="kbsm-business-readonly"><div>Pendapatan: <strong>Rp {{ number_format($shuKoperasi->total_pendapatan,0,',','.') }}</strong></div><div>Beban: <strong>Rp {{ number_format($shuKoperasi->total_biaya,0,',','.') }}</strong></div><div>Laba Bersih: <strong>Rp {{ number_format($shuKoperasi->shu_total,0,',','.') }}</strong></div><div>{{ $shuKoperasi->source_snapshot['jumlah_jurnal'] ?? $shuKoperasi->source_snapshot['journal_count'] ?? 0 }} jurnal posted</div></div></section>
  <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Proses Approval</h2></div>
   @if($shuKoperasi->status==='calculated')<form method="POST" action="{{ route('shu-koperasi.approve',$shuKoperasi) }}" class="kbsm-business-form">@csrf<input name="approval_reason" required minlength="5" maxlength="1000" placeholder="Dasar approval/RAT" class="kbsm-business-control"><button class="kbsm-btn kbsm-btn--green">Setujui Perhitungan</button></form>@endif
   @if($shuKoperasi->status==='approved')<form method="POST" action="{{ route('shu-koperasi.post',$shuKoperasi) }}">@csrf<button class="kbsm-btn kbsm-btn--green">Posting Alokasi SHU</button></form>@endif
   @if($shuKoperasi->status==='closed')<form method="POST" action="{{ route('shu-koperasi.reverse',$shuKoperasi) }}" class="kbsm-business-form">@csrf<input name="reversal_reason" required minlength="5" maxlength="1000" placeholder="Alasan koreksi resmi" class="kbsm-business-control"><button class="kbsm-btn kbsm-btn--outline-red">Reversal Alokasi</button></form>@endif
   <div class="kbsm-business-muted">Pembuat: {{ $shuKoperasi->creator?->name ?? '-' }} · Approver: {{ $shuKoperasi->approver?->name ?? '-' }} · Poster: {{ $shuKoperasi->poster?->name ?? '-' }}</div>
  </section>
 </div>
 <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Alokasi Berdasarkan Konfigurasi Efektif</h2></div><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Alokasi</th><th>Persentase</th><th>Nominal</th></tr></thead><tbody>
 @foreach([['Dana Cadangan','persen_dana_cadangan','nominal_dana_cadangan'],['SHU Anggota','persen_shu_anggota','nominal_shu_anggota'],['Pengurus','persen_pengurus','nominal_pengurus'],['Pengawas','persen_pengawas','nominal_pengawas'],['Pembina','persen_pembina','nominal_pembina'],['Dana Sosial','persen_dana_sosial','nominal_dana_sosial'],['Dana Pendidikan','persen_dana_pendidikan','nominal_dana_pendidikan']] as $row)<tr><td>{{ $row[0] }}</td><td>{{ number_format($shuKoperasi->{$row[1]},2,',','.') }}%</td><td><strong>Rp {{ number_format($shuKoperasi->{$row[2]},0,',','.') }}</strong></td></tr>@endforeach
 </tbody></table></div></section>
 <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Snapshot Pembagian Anggota</h2></div><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Anggota</th><th>Bobot Simpanan</th><th>Bobot Usaha</th><th>Jasa Modal</th><th>Jasa Usaha</th><th>Total SHU</th></tr></thead><tbody>@forelse($shuKoperasi->anggotaPembagian as $row)<tr><td>{{ $row->karyawan?->nama }}</td><td>Rp {{ number_format($row->total_simpanan,0,',','.') }}</td><td>Rp {{ number_format($row->total_transaksi_usaha,0,',','.') }}</td><td>Rp {{ number_format($row->nominal_jasa_modal,0,',','.') }}</td><td>Rp {{ number_format($row->nominal_jasa_usaha,0,',','.') }}</td><td><strong>Rp {{ number_format($row->nominal_shu,0,',','.') }}</strong></td></tr>@empty<tr><td colspan="6" class="kbsm-business-empty">Tidak ada anggota aktif dalam snapshot.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
