<?php
namespace App\Http\Controllers;
use App\Models\Anggota;use App\Models\DanaSosialLimit;use App\Models\DanaSosialSumber;use App\Models\DompetKoperasi;use App\Models\KlaimDanaSosial;use App\Services\SocialFundService;use Illuminate\Http\Request;use Illuminate\Validation\Rule;
class DanaSosialController extends Controller
{
 public function __construct(private readonly SocialFundService $service){}
 public function index(){$sources=DanaSosialSumber::query()->with(['shu.periode','dompet'])->latest('tanggal')->get();$approved=$sources->where('status','approved');return view('pages.dana-sosial.index',['sources'=>$sources,'claims'=>KlaimDanaSosial::query()->with(['anggota.karyawan','creator','approver','dompet'])->latest()->paginate(15),'limits'=>DanaSosialLimit::query()->orderBy('label')->get(),'members'=>Anggota::query()->with('karyawan')->where('status','aktif')->get(),'wallets'=>DompetKoperasi::query()->with('akun')->orderBy('nama_dompet')->get(),'socialSummary'=>['available'=>$approved->sum('saldo_tersedia'),'shu'=>$approved->where('jenis',DanaSosialSumber::JENIS_SHU)->sum('jumlah'),'donations'=>$approved->where('jenis',DanaSosialSumber::JENIS_DONASI)->sum('jumlah'),'approved_claims'=>KlaimDanaSosial::query()->whereIn('status',[KlaimDanaSosial::DISETUJUI,KlaimDanaSosial::DIBAYAR])->sum('nominal_diajukan'),'paid_claims'=>KlaimDanaSosial::query()->where('status',KlaimDanaSosial::DIBAYAR)->sum('nominal_diajukan')]]);}
 public function donation(Request $r){$d=$r->validate(['dompet_id'=>'required|exists:dompet_koperasi,id','jumlah'=>'required|integer|min:1','tanggal'=>'required|date','nomor_referensi'=>'nullable|string|max:120','keterangan'=>'required|string|max:1000']);$this->service->createDonation($d,(int)$r->user()->id);return back()->with('success','Donasi resmi dibuat dan menunggu persetujuan Admin lain.');}
 public function approveDonation(DanaSosialSumber $sumber){$this->service->approveDonation($sumber,(int)auth()->id());return back()->with('success','Donasi resmi disetujui dan dana masuk Kas/Bank.');}
 public function limit(Request $r){$d=$r->validate(['kategori'=>['required',Rule::in(['kematian','kelahiran','khitan','proposal_sosial'])],'label'=>'required|string|max:100','maksimal'=>'required|integer|min:1']);$this->service->saveLimit($d,(int)$r->user()->id);return back()->with('success','Batas kategori berhasil disimpan.');}
 public function claim(Request $r){$d=$r->validate(['anggota_id'=>'nullable|exists:anggota,id','penerima_manfaat'=>'required|string|max:150','kategori'=>['required',Rule::in(['kematian','kelahiran','khitan','proposal_sosial'])],'tanggal_kejadian'=>'required|date','nominal_diajukan'=>'required|integer|min:1','catatan'=>'nullable|string|max:1000','dokumen'=>'nullable|file|mimes:pdf,jpg,jpeg,png|max:5120']);if($r->hasFile('dokumen'))$d['dokumen_path']=$r->file('dokumen')->store('dana-sosial','public');unset($d['dokumen']);$this->service->createClaim($d,(int)$r->user()->id);return back()->with('success','Klaim dibuat dan menunggu persetujuan Admin lain.');}
 public function approveClaim(KlaimDanaSosial $klaim){$this->service->approveClaim($klaim,(int)auth()->id());return back()->with('success','Klaim Dana Sosial disetujui.');}
 public function payClaim(Request $r,KlaimDanaSosial $klaim){$d=$r->validate(['dompet_id'=>'required|exists:dompet_koperasi,id','metode_pembayaran'=>['required',Rule::in(['tunai','transfer_bank'])],'tanggal_bayar'=>'required|date','nomor_referensi'=>'nullable|string|max:120']);$this->service->payClaim($klaim,$d,(int)$r->user()->id);return back()->with('success','Klaim Dana Sosial berhasil dibayar.');}
}
