@extends('layout.main')
@section('content')
@php $money=fn($value)=>(float)$value===0.0?'–':'Rp '.number_format((float)$value,0,',','.'); $available=$socialSummary['available']; $shuAllocation=$socialSummary['shu']; $donations=$socialSummary['donations']; $approvedClaims=$socialSummary['approved_claims']; $paidClaims=$socialSummary['paid_claims']; $category=['kematian'=>'Kematian','kelahiran'=>'Kelahiran','khitan'=>'Khitan','proposal_sosial'=>'Proposal Sosial']; @endphp
<div class="kbsm-business-page">
 @if(session('success'))<div class="kbsm-business-alert kbsm-business-alert--success">{{ session('success') }}</div>@endif
 @if($errors->any())<div class="kbsm-business-alert kbsm-business-alert--danger">{{ $errors->first() }}</div>@endif
 <header class="kbsm-business-header"><div><p class="kbsm-business-eyebrow">SHU & Dana Sosial</p><h1 class="kbsm-business-title">Dana Sosial & Klaim</h1><p class="kbsm-business-subtitle">Dana bersumber dari alokasi SHU dan donasi resmi. Pembayaran klaim menggunakan sumber terlama lebih dahulu.</p></div><div class="kbsm-business-total"><span>Saldo Dana Tersedia</span><strong>{{ $money($available) }}</strong></div></header>
 <div class="kbsm-business-metrics"><article><span>Saldo Tersedia</span><strong>{{ $money($available) }}</strong></article><article><span>Alokasi dari SHU</span><strong>{{ $money($shuAllocation) }}</strong></article><article><span>Donasi Resmi Masuk</span><strong>{{ $money($donations) }}</strong></article><article><span>Klaim Disetujui / Dibayar</span><strong>{{ $money($approvedClaims) }} / {{ $money($paidClaims) }}</strong></article></div>
 <div class="kbsm-business-two-column">
  <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Catat Donasi Resmi</h2><p class="kbsm-business-panel__copy">Saldo Kas/Bank baru bertambah setelah disetujui Admin lain.</p></div><form method="POST" action="{{ route('dana-sosial.donation') }}" class="kbsm-form-grid">@csrf<div class="kbsm-field"><label>Kas / Bank Penerima</label><select name="dompet_id" required><option value="">Pilih dompet</option>@foreach($wallets as $wallet)<option value="{{ $wallet->id }}">{{ $wallet->nama_dompet }}</option>@endforeach</select></div><div class="kbsm-field"><label>Jumlah</label><input type="number" name="jumlah" min="1" required></div><div class="kbsm-field"><label>Tanggal</label><input type="date" name="tanggal" value="{{ now()->format('Y-m-d') }}" required></div><div class="kbsm-field"><label>Nomor Referensi</label><input name="nomor_referensi"></div><div class="kbsm-field kbsm-field--wide"><label>Keterangan</label><textarea name="keterangan" required></textarea></div><div class="kbsm-field kbsm-field--wide"><button class="kbsm-btn kbsm-btn--navy">Simpan Donasi</button></div></form></section>
  <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Batas Maksimal Manfaat</h2><p class="kbsm-business-panel__copy">Atur limit sebelum klaim pada kategori tersebut dibuat.</p></div><form method="POST" action="{{ route('dana-sosial.limit') }}" class="kbsm-form-grid">@csrf<div class="kbsm-field"><label>Kategori</label><select name="kategori" required>@foreach($category as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="kbsm-field"><label>Label</label><input name="label" required></div><div class="kbsm-field"><label>Maksimal</label><input type="number" name="maksimal" min="1" required></div><div class="kbsm-field"><button class="kbsm-btn kbsm-btn--outline-slate">Simpan Batas</button></div></form><div class="kbsm-business-list">@forelse($limits as $limit)<div><span>{{ $limit->label }}</span><strong>{{ $money($limit->maksimal) }}</strong></div>@empty<p class="kbsm-business-muted">Belum ada batas kategori.</p>@endforelse</div></section>
 </div>
 <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Ajukan Klaim</h2></div><form method="POST" action="{{ route('dana-sosial.claim') }}" class="kbsm-form-grid">@csrf<div class="kbsm-field"><label>Anggota (opsional)</label><select name="anggota_id"><option value="">Bukan anggota / umum</option>@foreach($members as $member)<option value="{{ $member->id }}">{{ $member->karyawan?->nama }} · {{ $member->nomor_anggota }}</option>@endforeach</select></div><div class="kbsm-field"><label>Penerima Manfaat</label><input name="penerima_manfaat" required></div><div class="kbsm-field"><label>Kategori</label><select name="kategori" required>@foreach($category as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="kbsm-field"><label>Tanggal Kejadian</label><input type="date" name="tanggal_kejadian" required></div><div class="kbsm-field"><label>Nominal Diajukan</label><input type="number" name="nominal_diajukan" min="1" required></div><div class="kbsm-field kbsm-field--wide"><label>Catatan</label><textarea name="catatan"></textarea></div><div class="kbsm-field kbsm-field--wide"><button class="kbsm-btn kbsm-btn--navy">Ajukan Klaim</button></div></form></section>
 <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Riwayat Klaim</h2></div><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Klaim</th><th>Penerima</th><th>Kategori</th><th class="kbsm-business-table__right">Nominal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($claims as $claim)<tr><td><span class="kbsm-business-code">{{ $claim->kode_klaim }}</span><div class="kbsm-business-muted">{{ $claim->tanggal_kejadian->format('d/m/Y') }}</div></td><td>{{ $claim->penerima_manfaat }}<div class="kbsm-business-muted">{{ $claim->anggota?->karyawan?->nama }}</div></td><td>{{ $category[$claim->kategori] ?? $claim->kategori }}</td><td class="kbsm-business-amount">{{ $money($claim->nominal_diajukan) }}</td><td><span class="kbsm-status {{ $claim->status==='dibayar'?'kbsm-status--green':'kbsm-status--gold' }}">{{ $claim->status_label }}</span></td><td>@if($claim->status==='menunggu_persetujuan')<form method="POST" action="{{ route('dana-sosial.claim.approve',$claim) }}" class="inline">@csrf<button class="kbsm-btn kbsm-btn--outline-slate kbsm-btn--sm">Setujui</button></form>@elseif($claim->status==='disetujui')<details><summary class="kbsm-btn kbsm-btn--navy kbsm-btn--sm">Bayar</summary><form method="POST" action="{{ route('dana-sosial.claim.pay',$claim) }}" class="kbsm-inline-form">@csrf<select name="metode_pembayaran"><option value="tunai">Tunai</option><option value="transfer_bank">Transfer Bank</option></select><select name="dompet_id" required><option value="">Pilih Kas/Bank</option>@foreach($wallets as $wallet)<option value="{{ $wallet->id }}">{{ $wallet->nama_dompet }}</option>@endforeach</select><input type="date" name="tanggal_bayar" value="{{ now()->format('Y-m-d') }}" required><input name="nomor_referensi" placeholder="Nomor referensi"><button class="kbsm-btn kbsm-btn--navy kbsm-btn--sm">Catat Pembayaran</button></form></details>@elseif($claim->status==='dibayar')<span class="kbsm-business-muted">{{ $claim->tanggal_bayar?->format('d/m/Y') }} · {{ $claim->dompet?->nama_dompet }}</span>@endif</td></tr>@empty<tr><td colspan="6" class="kbsm-business-empty">Belum ada klaim Dana Sosial.</td></tr>@endforelse</tbody></table></div><div class="kbsm-business-pagination">{{ $claims->links() }}</div></section>
 <section class="kbsm-business-panel"><div class="kbsm-business-panel__header"><h2 class="kbsm-business-panel__title">Sumber Dana</h2></div><div class="kbsm-business-table-wrap"><table class="kbsm-business-table"><thead><tr><th>Kode</th><th>Jenis</th><th>Tanggal</th><th class="kbsm-business-table__right">Nilai Awal</th><th class="kbsm-business-table__right">Saldo</th><th>Status / Aksi</th></tr></thead><tbody>@forelse($sources as $source)<tr><td><span class="kbsm-business-code">{{ $source->kode_sumber }}</span></td><td>{{ $source->jenis==='alokasi_shu'?'Alokasi SHU':'Donasi Resmi' }}</td><td>{{ $source->tanggal->format('d/m/Y') }}</td><td class="kbsm-business-amount">{{ $money($source->jumlah) }}</td><td class="kbsm-business-amount">{{ $money($source->saldo_tersedia) }}</td><td>@if($source->status==='pending')<form method="POST" action="{{ route('dana-sosial.donation.approve',$source) }}" class="inline">@csrf<button class="kbsm-btn kbsm-btn--outline-slate kbsm-btn--sm">Setujui Donasi</button></form>@else<span class="kbsm-status kbsm-status--green">Disetujui</span>@endif</td></tr>@empty<tr><td colspan="6" class="kbsm-business-empty">Belum ada sumber Dana Sosial.</td></tr>@endforelse</tbody></table></div></section>
</div>
<script>
document.addEventListener('DOMContentLoaded',()=>{const form=document.querySelector('form[action="{{ route('dana-sosial.claim') }}"]');if(!form)return;form.enctype='multipart/form-data';const notes=form.querySelector('[name="catatan"]')?.closest('.kbsm-field');if(notes){const field=document.createElement('div');field.className='kbsm-field kbsm-field--wide';field.innerHTML='<label>Dokumen Pendukung (opsional)</label><input type="file" name="dokumen" accept=".pdf,.jpg,.jpeg,.png"><div class="kbsm-business-muted">PDF/JPG/PNG, maksimal 5 MB.</div>';notes.after(field);}});
</script>
@endsection
